/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE clientiBaseService PLEASE EDIT ../clienti.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Clienti } from '../../domain/laboratorio_db/clienti';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../Clienti.service.ts
 */

/*
 * SCHEMA DB Clienti
 *
	{
		Cognome: {
			type: 'String',
			required : true
		},
		Email: {
			type: 'String'
		},
		Nome: {
			type: 'String',
			required : true
		},
		Telefono: {
			type: 'String',
			required : true
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		CliKey: {
			type: Schema.ObjectId,
			ref : "InterventiT"
		},
	}
 *
 */
@Injectable()
export class ClientiBaseService {

    contextUrl: string = environment.endpoint + '/clienti';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * ClientiService.create
    *   @description CRUD ACTION create
    *   @param Clienti obj Object to insert
    *
    */
    create(item: Clienti): Observable<Clienti> {
        return this.http
            .post<Clienti>(this.contextUrl, item)
            .pipe(map(data => data));
    }

    /**
    * ClientiService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id Clienti
    *
    */
    remove(id: string): Observable<void> {
        return this.http
            .delete<void>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * ClientiService.list
    *   @description CRUD ACTION list
    *   @returns ARRAY OF Clienti
    *
    */
    list(): Observable<Clienti[]> {
        return this.http
            .get<Clienti[]>(this.contextUrl)
            .pipe(map(data => data));
    }

    /**
    * ClientiService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id Clienti
    *   @returns Clienti
    *
    */
    update(item: Clienti): Observable<Clienti> {
        return this.http
            .post<Clienti>(this.contextUrl + '/' + item._id, item)
            .pipe(map(data => data));
    }


    // Custom APIs

}
