/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE interventi-tBaseService PLEASE EDIT ../interventi-t.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { InterventiT } from '../../domain/laboratorio_db/interventi-t';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../InterventiT.service.ts
 */

/*
 * SCHEMA DB InterventiT
 *
	{
		Cliente: {
			type: 'String',
			required : true
		},
		Data: {
			type: 'Date',
			required : true
		},
		Difetto: {
			type: 'String'
		},
		Numero: {
			type: 'Number',
			required : true,
			enum : ["1"]
		},
		Stato: {
			type: 'String',
			required : true
		},
		Tecnico: {
			type: 'String',
			required : true
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		CliKey: {
			type: Schema.ObjectId,
			ref : "InterventiT"
		},
	}
 *
 */
@Injectable()
export class InterventiTBaseService {

    contextUrl: string = environment.endpoint + '/interventit';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS


    // Custom APIs

}
