/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE interventi-rBaseService PLEASE EDIT ../interventi-r.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { InterventiR } from '../../domain/laboratorio_db/interventi-r';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../InterventiR.service.ts
 */

/*
 * SCHEMA DB InterventiR
 *
	{
		Costo: {
			type: 'Decimal'
		},
		Descrizione: {
			type: 'String'
		},
		Prezzo: {
			type: 'Decimal'
		},
		Qnt: {
			type: 'Decimal'
		},
		Totale: {
			type: 'Decimal'
		},
		Um: {
			type: 'String'
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		ArtKey: {
			type: Schema.ObjectId,
			ref : "InterventiR"
		},
	}
 *
 */
@Injectable()
export class InterventiRBaseService {

    contextUrl: string = environment.endpoint + '/interventir';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS


    // Custom APIs

}
